/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include "qsk_bsp.h"
#include "qsk_lcd.h"
#include "stdio.h"

// prototypes

void mcu_init(void);	              
/*
void strings_and_ints(void);
void floats(void);
void more_ints(void);
*/
/* *******************************************************************
 Description:
 Entry:
 Returns:
 
 Notes:
 
***********************************************************************/ 
void main(void)
{
	
	mcu_init();
//	InitDisplay();
//	DisplayString(LCD_LINE1, "Hi World");
//	strings_and_ints();
//	floats();
//	more_ints();
	
	while (1)
		;
}

/*void strings_and_ints(void){
	char s1[30], s2[30];
	int a=5, b=10, c=-30;
	char ch='$';

	sprintf(s1, "Testing");
	sprintf(s2, "a=%d, b=%d", a, b);
	sprintf(s1, "b=%x, c=%d", b, c);
	sprintf(s1, "b=0x%x", b);
	sprintf(s2, "s1=%s", s1);
	sprintf(s1, "%c %c" , ch, s2[0]);
}

void floats(void) {
	float f1=3.14, f2=9.991, f3=-19110.331;
	char s1[30], s2[30];
	
	sprintf(s1, "%f", f1);
	sprintf(s1, "%f", f3);
	sprintf(s1, "%4.1f", f2);
}

void more_ints(void) {
	int a=442, b=1, c=-11;
	char s1[30], s2[30];

	sprintf(s1, "%5d", a);
	sprintf(s1, "%-4d", b);
	sprintf(s1, "%4d", b);
	sprintf(s1, "%-5.4d", c);
}*/
