// tab space = 4
/***********************************************************************/
/*                                                                     */
/*  FILE        :main_qsk26a_template.c                                 */
/*  DATE        :July 6, 2004	                                       */
/*  DESCRIPTION :Main Program                                          */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
                  
#include "qsk_bsp.h"	 // include QSK board support package
#include "qsk_lcd.h"
#include "stdio.h"

/* Prototype declarations */
void mcu_init(void);	 // MCU initialization

/******************************************************************************
Name       : main
Parameters : none
Returns    : nothing
Description: Main template
******************************************************************************/
void main(void)
{
	
	mcu_init();			// Initialize MCU
	InitDisplay();
	DisplayString(LCD_LINE1, "Hi World");
	DisplayString(LCD_LINE2, "smdupor");
	GRN_LED=LED_ON;
 //   GRN_LED=LED_OFF;
	while(1)
	{
		_asm ("NOP");
	}
}

/**************************************************************************
Name       : mcu_init()   
Parameters : none                   
Returns    : nothing      
Description: The starter kit startup file initializes the clock circuit
             to the main crystal with a divide by 1.  This function
             enables the PLL 
             The function also sets the LED as an output port   
***************************************************************************/
void mcu_init(void)
{
  {
    prc1 = 1;                       /* enable access to processor mode registers */
    pm20 = 0;                       /* 2 wait states for sfr access...this is the reset value
                                       necessary for >16Mhz operation, can be set to 1 wait for <=16Mhz */
    prc1 = 0;                       /* disable access to processor mode registers */
  }

  {
    /* configure and switch main clock to PLL at 20MHz */
    unsigned int count = 20000;
    prc0 = 1;                       /* enable access to clock registers */
    cm1 = 0x20;                     /* set to hi-drive Xin, divide by 1 */
    cm0 = 0x08;                     /* set to main clock using divide by 1 */
    cm21 = 0;                       /* switch to Xin */
    plc0 = 0x11;                    /* configure PLL to x2 */
    plc0 = 0x91;                    /* enable PLL */
    while(count > 0) count--;       /* wait for PLL to stabilize (20mS maximum, 200,000 cycles @10Mhz)
                                       this decrement with no optimization is 12 cycles each (20,000*12 cycles=240,000=24mS) */
    cm11 = 1;                       /* switch to PLL */
    prc0 = 0;                       /* disable access to clock registers */
  }
   
  /* LED initialization for this demo - macro defined in QSK_bsp.h */
  ENABLE_LEDS;
}
